messages:
    info:
      start: |
        üëã –ü—Ä–∏–≤–µ—Ç! –î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å –≤ <b>LangBRV</b>. 
        –Ø –±–æ—Ç, –∫–æ—Ç–æ—Ä—ã–π –ø–æ–º–æ–∂–µ—Ç —Ç–µ–±–µ –≤ –∏–∑—É—á–µ–Ω–∏–∏ –∞–Ω–≥–ª–∏–π—Å–∫–æ–≥–æ —è–∑—ã–∫–∞!

        ‚Ä¢ üìö <b><i>–°–ª–æ–≤–∞—Ä—å:</i></b>
        –¢—ã –º–æ–∂–µ—à—å —Å–æ—Ö—Ä–∞–Ω–∏—Ç—å –ª—é–±–æ–µ —Å–ª–æ–≤–æ –∏–ª–∏ —Å–ª–æ–≤–æ—Å–æ—á–µ—Ç–∞–Ω–∏–µ –≤ —Å–≤–æ–π –ª–∏—á–Ω—ã–π —Å–ª–æ–≤–∞—Ä—å! –ë–æ–ª—å—à–µ –Ω–∏–∫–∞–∫–∏—Ö –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–π –∏ –±–ª–æ–∫–Ω–æ—Ç–æ–≤, –≤—Å–µ —É —Ç–µ–±—è –≤ —Ç–µ–ª–µ–≥—Ä–∞–º–º–µ.

        ‚Ä¢ üß† <b><i>–ü–æ–≤—Ç–æ—Ä–µ–Ω–∏–µ:</i></b>
        –ö–∞–∂–¥—ã–π –¥–µ–Ω—å —Ç—ã –º–æ–∂–µ—à—å –ø–æ–≤—Ç–æ—Ä—è—Ç—å –¥–æ–±–∞–≤–ª–µ–Ω–Ω—ã–µ —Ç–æ–±–æ–π —Å–ª–æ–≤–∞! –Ø —Å–∞–º –ø–æ–¥–±–µ—Ä—É, —á—Ç–æ –∏–º–µ–Ω–Ω–æ –Ω—É–∂–Ω–æ –æ—Å–≤–µ–∂–∏—Ç—å –≤ –ø–∞–º—è—Ç–∏, —Å –ø–æ–º–æ—â—å—é —Å–ø–µ—Ü–∏–∞–ª—å–Ω–æ–π —Ç–µ—Ö–Ω–∏–∫–∏ –∏–Ω—Ç–µ—Ä–≤–∞–ª—å–Ω–æ–≥–æ –ø–æ–≤—Ç–æ—Ä–µ–Ω–∏—è.

        üëà –í—Å–µ –¥–æ—Å—Ç—É–ø–Ω—ã–µ –∫–æ–º–∞–Ω–¥—ã –µ—Å—Ç—å –≤ –º–µ–Ω—é —Å–ª–µ–≤–∞.

        üî• –ù–µ –æ—Ç–∫–ª–∞–¥—ã–≤–∞–π –∏–∑–º–µ–Ω–µ–Ω–∏—è –∫ –ª—É—á—à–µ–º—É - –¥–æ–±–∞–≤–ª—è–π —Å–≤–æ—ë –ø–µ—Ä–≤–æ–µ —Å–ª–æ–≤–æ!
        
        üòâ –£–¥–∞—á–∏! 

      add_word: |
        ‚úçÔ∏è –í–≤–µ–¥–∏ –Ω–æ–≤–æ–µ —Å–ª–æ–≤–æ –≤ —Ñ–æ—Ä–º–∞—Ç–µ
        —Å–ª–æ–≤–æ-–ø–µ—Ä–µ–≤–æ–¥

        –ù–∞–ø—Ä–∏–º–µ—Ä: sun-—Å–æ–ª–Ω—Ü–µ

        <i>P.S. –ú–æ–∂–µ—à—å –¥–∞–∂–µ –Ω–µ –ø–∏—Å–∞—Ç—å –∫–æ–º–∞–Ω–¥—É - –ø—Ä–æ—Å—Ç–æ –æ—Ç–ø—Ä–∞–≤–ª—è–π –º–Ω–µ –ø–∞—Ä—ã —Å–ª–æ–≤ –≤ —Ç–∞–∫–æ–º –≤–∏–¥–µ, —è –≤—Å–µ –ø–æ–π–º—É üòâ</i>"
      del_word: "üóë –í–≤–µ–¥–∏ —Å–ª–æ–≤–æ, –∫–æ—Ç–æ—Ä–æ–µ —Ö–æ—á–µ—à—å —É–¥–∞–ª–∏—Ç—å –∏–∑ —Å–≤–æ–µ–≥–æ —Å–ª–æ–≤–∞—Ä—è"
    success:
      word_added: "‚úÖ –°–ª–æ–≤–æ –¥–æ–±–∞–≤–ª–µ–Ω–æ –≤ —Ç–≤–æ–π —Å–ª–æ–≤–∞—Ä—å"
      word_deleted: "‚úÖ –°–ª–æ–≤–æ —É–¥–∞–ª–µ–Ω–æ"
    errors:
      unknown: "üò® –û—à–∏–±–∫–∞...\n–ò–∑–≤–∏–Ω–∏, —è –Ω–µ–º–Ω–æ–≥–æ –ø—Ä–∏–±–æ–ª–µ–ª, –ø–æ–≤—Ç–æ—Ä–∏ –∑–∞–ø—Ä–æ—Å –ø–æ–ø–æ–∑–∂–µ"
      unknown_command: "üò® –¢–∞–∫—É—é –∫–æ–º–∞–Ω–¥—É —è –Ω–µ –∑–Ω–∞—é :(\n–°–ø–∏—Å–æ–∫ –∫–æ–º–∞–Ω–¥ –º–æ–∂–Ω–æ –ø–æ—Å–º–æ—Ç—Ä–µ—Ç—å –≤ –º–µ–Ω—é —Å–ª–µ–≤–∞"
      unknown_msg: "üòî –ù–µ –ø–æ–Ω–∏–º–∞—é —Ç–µ–±—è.\n–ü–æ—Å–º–æ—Ç—Ä–∏, —á—Ç–æ —è —É–º–µ—é –≤ –º–µ–Ω—é —Å–ª–µ–≤–∞"
      no_words: "üòâ –í —Ç–≤–æ—ë–º —Å–ª–æ–≤–∞—Ä–µ –ø–æ–∫–∞ –Ω–µ—Ç —Å–ª–æ–≤, –Ω–æ —Ç—ã –≤—Å–µ–≥–¥–∞ –º–æ–∂–µ—à—å —ç—Ç–æ –∏—Å–ø—Ä–∞–≤–∏—Ç—å :)"
      no_words_to_remind: "ü¶¶ –°–µ–≥–æ–¥–Ω—è –Ω–µ—Ç —Å–ª–æ–≤ –Ω–∞ –ø–æ–≤—Ç–æ—Ä–µ–Ω–∏–µ, –º–æ–∂–Ω–æ –æ—Ç–¥–æ—Ö–Ω—É—Ç—å"
      word_not_exists: "ü§∑‚Äç‚ôÇÔ∏è –¢–∞–∫–æ–≥–æ —Å–ª–æ–≤–∞ –Ω–µ—Ç –≤ —Ç–≤–æ–µ–º —Å–ª–æ–≤–∞—Ä–µ"
      word_too_long: "ü´£ –°–ª–æ–≤–æ –æ—á–µ–Ω—å –¥–ª–∏–Ω–Ω–æ–µ, —Ç–∞–∫–æ–µ —è –Ω–µ –ø–µ—Ä–µ–≤–∞—Ä—é"
      missing_separator: "üòâ –ö–∞–∂–µ—Ç—Å—è, —Ç—ã –ø—Ä–æ–ø—É—Å—Ç–∏–ª —á–µ—Ä—Ç–æ—á–∫—É –º–µ–∂–¥—É —Å–ª–æ–≤–∞–º–∏"

telegram:
  update_timeout: 30
