messages:
    info:
      start: "Привет, это LANGBRV, бот для изучения английского языка! Напиши /add_word чтобы добавить первое слово!"
      add_word: "Введи слово в формате слово-перевод"
    success:
      word_added: "Слово сохранено"
      word_deleted: "Слово удалено"
    errors:
      unknown: "Неизвестная ошибка"
      unknown_command: "Такую команду я не знаю"
      no_words: "В словаре пока нет слов.\nЧтобы добавить слово напиши /add_word"
      no_words_to_remind: "Сегодня нет слов на повторение"
telegram:
  update_timeout: 30
